# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 08:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('complete', models.BooleanField()),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date', 'time'),
            },
        ),
        migrations.CreateModel(
            name='RepairComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoshop.Repair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('repair', 'date'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='repaircomment',
            unique_together=set([('repair', 'user', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='repair',
            unique_together=set([('date', 'time')]),
        ),
    ]
