# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 05:01
from __future__ import unicode_literals

import autoshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair',
            name='complete',
        ),
        migrations.AddField(
            model_name='repair',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Complete'), (2, 'Approved')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repair',
            name='time',
            field=models.TimeField(blank=True, null=True, validators=[autoshop.models.validate_time_ends_in_zero]),
        ),
    ]
