const constants = {
  // Action types
  ADD_REPAIR: 'ADD_REPAIR',
  EDIT_REPAIR: 'EDIT_REPAIR',
  REMOVE_REPAIR: 'REMOVE_REPAIR',
  ADD_USER: 'ADD_USER',
  EDIT_USER: 'EDIT_USER',
  REMOVE_USER: 'REMOVE_USER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',

  // Roles
  SUPERUSER: 'SUPERUSER',
  NORMAL_USER: 'NORMAL_USER',
};
export default constants;
