const constants = {
  // Action types
  ADD_REPAIR: 'ADD_REPAIR',
  EDIT_REPAIR: 'EDIT_REPAIR',
  REMOVE_REPAIR: 'REMOVE_REPAIR',
  ADD_USER: 'ADD_USER',
  EDIT_USER: 'EDIT_USER',
  REMOVE_USER: 'REMOVE_USER',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CHANGE_LOGIN_FORM: 'CHANGE_LOGIN_FORM',
  START_FETCHING_USERS: 'START_FETCHING_USERS',
  FETCHED_USERS: 'FETCHED_USERS',
  SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',

  // Roles
  SUPERUSER: 'SUPERUSER',
  NORMAL_USER: 'NORMAL_USER',
};
export default constants;
